### ISSUE TITLE
limite de rows en sheet 1048576 libreoffice programar funcion para que salte de hoja

### ISSUE THREAD

**Issue by jorgepachon** [turulomio/unogenerator#91]
max_rows=1048000 #Maximas lineas que puede tener una hoja en localc
        ceil_=ceil(len(lor)/max_rows)
        for num_sheet in range(ceil_):
            if ceil_>1:
                doc.createSheet(f"Registro {num_sheet+1} de {ceil_}")
                print(f"Más de {max_rows} filas particionando en {ceil_} hojas")
            else:
                doc.createSheet("Registro")
            fields=[]
            doc.addRowWithStyle("A2", fields, ColorsNamed.Yellow, "BoldCenter")
            doc.setColumnsWidth([3, 4, 3, 3, 3, 3, 5, 15, 5, 5, 15, 6, 6])           
            from_=max_rows*num_sheet
            to_=max_rows*(num_sheet+1) if len(lor)>=max_rows*(num_sheet+1) else len(lor)
            doc.addListOfRowsWithStyle("A3", lor[from_:to_])
            doc.freezeAndSelect("F3")

**Comment by turulomio** [comment]
Created helper_split_big_listofrows method in unogenerator.helpers
